<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<DisableNuGetAudit>true</DisableNuGetAudit>
		<!--<Nullable>enable</Nullable>-->
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Jobs\" />
		<Folder Include="http\" />
		<Folder Include="Socket\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Coravel" Version="6.0.2" />
		<PackageReference Include="Google.Protobuf" Version="3.33.0" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Grpc.Tools" Version="2.76.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\MizeBazi.Store.Common\MizeBazi.Store.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\user.proto" GrpcServices="Both" />
	</ItemGroup>

</Project>
